services:
  webserver:
    image: nginx
    volumes:
    - ./app:/var/www/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./app:/var/www/html